"use client";
import { useEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";
import { learningStore } from "@/lib/learningStore";
export default function EbookReader(){const frame=useRef<HTMLIFrameElement>(null),selected=useRef<File|null>(null),key=useRef(""),account=useRef("");const[ready,setReady]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==frame.current?.contentWindow||event.origin!=="null")return;if(event.data?.type==="rb-epub-ready")setReady(true);if(event.data?.type==="rb-epub-progress"&&typeof event.data.cfi==="string"&&event.data.cfi.length<4000&&key.current&&account.current)void learningStore.books.put({key:key.current,account:account.current,cfi:event.data.cfi}).catch(()=>undefined);};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive);},[]);
  async function open(file:File){if(file.size>20_000_000||!file.name.toLowerCase().endsWith(".epub")){setMessage("Pilih EPUB tanpa DRM, maksimal 20 MB.");return;}const bytes=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(b=>b.toString(16).padStart(2,"0")).join("");const session=(await supabase.auth.getSession()).data.session;account.current=session?.user.id||"";key.current=account.current+":"+hash;const saved=account.current?await learningStore.books.get(key.current):null;frame.current?.contentWindow?.postMessage({type:"rb-open-epub",bytes,cfi:saved?.cfi||""},"*",[bytes]);setMessage(account.current?"Posisi baca disimpan di perangkat ini untuk akunmu.":"Buku dibuka lokal. Login diperlukan untuk menyimpan posisi baca.");}
  return <section className="learningPanel"><h2>Pembaca EPUB</h2><p>Buku milikmu yang bebas DRM dibaca lokal dalam sandbox terpisah. Tidak menambah bahan RAG secara otomatis.</p><input aria-label="Pilih buku EPUB" type="file" accept=".epub,application/epub+zip" disabled={!ready} onChange={e=>{selected.current=e.target.files?.[0]||null;if(selected.current)void open(selected.current).catch(e=>setMessage(e.message));}}/><p role="status">{ready?message:"Menyiapkan pembaca terisolasi…"}</p><iframe ref={frame} title="Pembaca EPUB terisolasi" sandbox="allow-scripts" src="/ebook-reader.html" style={{width:"100%",height:650,border:0}}/></section>;
}
